3 PICK 선생님 출석확인상세 페이지 퍼블리싱
DSM-PICK/PICK2023_FRONT_TEACHER pull request #12
Opened 2023-01-24 13:33 UTC by Aodtn

close #3

2023-01-24 14:03 UTC, potatovllage requested changes

2023-01-24 14:03 UTC, potatovllage commented on src/components/studentState/index.tsx
> +        {number} {name}
글자 들어가는 부분인 것 같은데 p 태그 쓰는게 어떨까요?

2023-01-24 14:03 UTC, potatovllage commented on src/components/studentState/index.tsx
> +      <StateBox ref={Ref}>{state}</StateBox>
이 부분도 마찬가지로 p 태그

2023-01-24 14:06 UTC, Aodtn commented on src/components/studentState/index.tsx
> +import { Theme } from "@emotion/react";
안쓰는겁니다. 수정하겠습니다.

2023-01-24 14:06 UTC, Aodtn commented on src/components/studentState/index.tsx
> +        {number} {name}
넵

2023-01-24 14:07 UTC, Aodtn commented on src/components/studentState/index.tsx
> +      <StateBox ref={Ref}>{state}</StateBox>
알겠습니다

2023-01-24 14:23 UTC, justinlee05 commented on src/components/studentState/index.tsx
> +          current.style.backgroundColor = "#9650fa";
useTheme 사용해보는거 추천드려요
물론 테마에 없을지도 모르지만
있다면요

2023-01-24 14:40 UTC, Aodtn commented on src/components/studentState/index.tsx
> +          current.style.backgroundColor = "#9650fa";
공부하고 사용해보겠습니다

2023-01-25 06:56 UTC, justinlee05 commented on src/components/studentState/index.tsx
> +          current.style.backgroundColor = "#9650fa";
커스텀 Hook이에요
const theme = useTheme();
요래놓고 쓰심 됨

2023-01-25 07:36 UTC, kimulchan commented on src/components/studentState/index.tsx
> +  });
https://velog.io/@chloeee/%EB%B2%88%EC%97%AD-If-elseswitch%EB%A5%BC-%EC%93%B0%EC%A7%80%EB%A7%90%EA%B3%A0-Object-Literals%EB%A5%BC-%EC%8D%A8%EB%9D%BC

이렇게 고칠 수 있으면 한번 고쳐봐바

2023-01-25 07:37 UTC, kimulchan commented on src/pages/attendanceDetails/index.tsx
> +            />
data 비구조화 할당을 하고 props 로 넘기자

2023-01-25 11:51 UTC, Aodtn commented on src/components/studentState/index.tsx
> +          current.style.backgroundColor = "#9650fa";
의찬선배님이 해보라고 하신 방법대로 했습니다

2023-01-25 12:43 UTC, potatovllage approved these changes

2023-01-26 08:04 UTC, justinlee05 approved these changes

2023-01-26 12:34 UTC, merged